#!/bin/sh

if [ -f $1 ] ; then
    case $1 in
        *.tar.bz2) tar xjf $1 ;;
        *.tar.gz)  tar xzf $1 ;;
        *.tar.xz)  tar -Jxvf $1 ;;
        *.txz)     tar -Jxvf $1 ;;
        *.bz2)     bunzip2 $1 ;;
        *.rar)     rar x $1 ;;
        *.gz)      gunzip $1 ;;
        *.tar)     tar xf $1 ;;
        *.tbz2)    tar xjf $1 ;;
        *.tgz)     tar xzf $1 ;;
        *.zip)     unzip $1 ;;
        *.Z)       uncompress $1 ;;
        *.7z)      7z x $1 ;;
        *.ace)     unace x $1 ;;
        
        *) echo 'Could not extract the file' ;;
    esac
else
    echo 'Is not a valid file'
fi
